name: Composite Action Template
description: Get started with Composite actions
branding:
  icon: award
  color: green
inputs:
  repo-token:
    description: 'A token for the repository'
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - id: greet
      run: |
        GREET="Hello ${WHO}"
        echo "${GREET}"
        echo "${GREET}" > greet.txt
        echo "word=${GREET}" >> $GITHUB_OUTPUT
      shell: bash
      env:
        WHO: ${{ inputs.who-to-greet }}
