name: Delete Action Cache
description: Delete GitHub Actions Cache after a pull request is closed
author: 'toshimaru'
branding:
  icon: 'trash'
  color: 'gray-dark'
inputs:
  github-token:
    description: 'A token for the repository'
    default: ${{ github.token }}
  head-ref:
    description: 'The value of `github.head_ref`'
    default: ${{ github.head_ref }}
  pr-number:
    description: 'A number of the Pull Request'
    default: ${{ github.event.number }}
  repo:
    description: 'The repository name'
    default: ${{ github.repository }}
runs:
  using: composite
  steps:
    - name: Delete GitHub Actions Cache
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        GH_REPO: ${{ inputs.repo }}
      run: |
        # Delete pull request caches
        for id in $(gh cache list --ref refs/pull/${{ inputs.pr-number }}/merge --json id --jq '.[].id'); do
          gh cache delete $id
          echo "Cache deleted. (id: $id)"
        done

        # Delete branch caches
        for id in $(gh cache list --ref refs/heads/${{ inputs.head-ref }} --json id --jq '.[].id'); do
          gh cache delete $id
          echo "Cache deleted. (id: $id)"
        done
