name: Composite Action Template
description: Get started with Composite actions
branding:
  icon: 'trash'
  color: 'gray-dark'
inputs:
  repo-token:
    description: 'A token for the repository'
    default: ${{ github.token }}
  branch:
    description: 'A branch name for the cache deletion'
    default: ${{ github.ref }}
  pr-number:
    description: 'A number of the Pull Request'
    default: ${{ github.event.number }}
runs:
  using: composite
  steps:
    - name: Delete GtiHub Actions Cache
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        echo "${{ inputs.branch }}"
        echo "${{ inputs.pr-number }}"
        gh cache list --json id,key,ref
