name: Delete Action Cache
description: Delete GitHub Actions Cache after a pull request is closed
author: 'toshimaru'
branding:
  icon: 'trash'
  color: 'gray-dark'
inputs:
  github-token:
    description: 'A token for the repository'
    default: ${{ github.token }}
  head-ref:
    description: 'The value of `github.head_ref`'
    default: ${{ github.head_ref }}
  pr-number:
    description: 'A number of the Pull Request'
    default: ${{ github.event.number }}
runs:
  using: composite
  steps:
    - name: Delete GitHub Actions Cache
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        echo "${{ inputs.head-ref }}"
        echo "${{ inputs.pr-number }}"
        gh cache list --json id,key,ref
