name: Create Tag
on:
  push:
    branches:
      - main
    paths:
      - 'VERSION'
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Create a tag based on the VERSION file
        uses: salsify/action-detect-and-tag-new-version@v2
        id: tag-new-version
        with:
          version-command: cat VERSION
