name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - name: Run Action without parameters
        uses: ./
      - name: Run Action with parameters
        uses: ./
        with:
          limit: 1
          head-ref: head_ref value
          pr-number: 0
          ref: ref value
          repo: ${{ github.repository }}
