name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  generate-cache:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16, 17, 18, 19, 20, 21, 22]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: "fixture"
  delete-cache:
    runs-on: ubuntu-latest
    needs: generate-cache
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - name: Run Action without parameters
        uses: ./
      - name: Run Action with parameters
        uses: ./
        with:
          limit: 1
          head-ref: head_ref value
          pr-number: 0
          ref: ref value
          repo: ${{ github.repository }}
