name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test-bash:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - id: without-parameters
        uses: ./
      - run: test "${GREET}" = "Hello World"
        env:
          GREET: ${{ steps.without-parameters.outputs.greet }}
      - run: test "$(cat greet.txt)" = "Hello World"
      - id: with-parameters
        uses: ./
        with:
          who-to-greet: composite action
      - run: test "${GREET}" = "Hello composite action"
        env:
          GREET: ${{ steps.with-parameters.outputs.greet }}
      - run: test "$(cat greet.txt)" = "Hello composite action"
