name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  generate-cache:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        package-manager: [npm, yarn]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: ${{ matrix.package-manager }}
          cache-dependency-path: "fixture"
  delete-cache:
    runs-on: ubuntu-latest
    needs: generate-cache
    permissions:
      actions: write
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - name: Run Action with limit 1
        uses: ./
        with:
          limit: 1
      - name: Run Action with parameters
        uses: ./
        with:
          github-token: ${{ github.token }}
          limit: 10
          head-ref: head_ref value
          pr-number: 0
          ref: ref value
          repo: ${{ github.repository }}
      - name: Run Action with branch
        uses: ./
        with:
          limit: 1
          branch: main
